events {}

http {
  upstream frontend_app {
    server interview_frontend:4173;
  }

  upstream backend_app {
    server interview_backend:8000;
  }

  server {
    listen 80;
    client_max_body_size 50m;

    location /api/ {
      proxy_pass http://backend_app/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /docs {
      proxy_pass http://backend_app/docs;
    }

    location /redoc {
      proxy_pass http://backend_app/redoc;
    }

    location /openapi.json {
      proxy_pass http://backend_app/api/v1/openapi.json;
    }

    location /uploads/ {
      proxy_pass http://backend_app/uploads/;
    }

    location / {
      proxy_pass http://frontend_app/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
